[package]
name = "lsuser"
version = "0.4.2"
edition = "2021"
description = "List system users in a clean, columnar layout using raw POSIX libc calls."
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/Vincent4486/lsuser"
keywords = ["cli", "sysadmin", "macos", "linux", "libc"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"